[package]
name = "personal-site"
version = "0.1.0"
authors = ["Evan Almloff <evanalmloff@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-web = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus = { git = "https://github.com/dioxuslabs/dioxus" }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
