[application]

# App (Project) Name
name = "personal site"

# Dioxus App Default Platform
# desktop, web, mobile, ssr
default_platform = "web"

# `build` & `serve` dist path
out_dir = "docs"

# resource (public) file folder
asset_dir = "public"

[web.app]

# HTML title tag content
title = ""

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "docs/output.css"]
